# Generated by Django 3.0.6 on 2020-06-11 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PyTraker', '0006_auto_20200611_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timers',
            name='taskID',
        ),
        migrations.AddField(
            model_name='timers',
            name='Project',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='PyTraker.Projects'),
        ),
    ]
